LOG_LEVEL: info
HTTP_SERVER_PORT: 8080
WORKER_ENABLED: true
DIRECTORY_PATH: "/Users/prateekcelly/Desktop/file-server"
JOB_NAME: "send_message"

STANDALONE_REDIS_HOST: "localhost:6379"
STANDALONE_REDIS_POOL_SIZE: 10
STANDALONE_REDIS_POOL_TIMEOUT_MS: 100
